export const types = {
  FETCH_FORM_FIELDS: 'FETCH_FORM_FIELDS',
  LOAD_FORM_DATA: 'LOAD_FORM_DATA',
  GET_FORM_FIELDS: 'GET_FORM_FIELDS',
  HANDLE_TEXT_INPUT: 'HANDLE_TEXT_INPUT',
  HANDLE_RADIO_INPUT: 'HANDLE_RADIO_INPUT',
  HANDLE_CHECKBOX_INPUT: 'HANDLE_CHECKBOX_INPUT',
  HANDLE_SUBMIT_FORMDATA: 'HANDLE_SUBMIT_FORMDATA',
  LOG_INPUT_CHANGES: 'LOG_INPUT_CHANGES'
}

export const fieldTypes = {
  inputText: 'inputText',
  radioGroup: 'radioGroup',
  checkboxGroup: 'checkboxGroup'
}
